# Generated by Django 5.2.5 on 2025-09-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_is_verified_profile_verification_token_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='request',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='requests/'),
        ),
    ]
